In [1]:
import torch

In [2]:
"""
gather 사용법
내가 원하는 축을 제외한 곳은 기존 텐서와 모양을 같게 맞춘다
내가 원하는 축의 index는 축을 기준으로 한 데이터 수와 같아야 한다
gather 후 원하는 축을 squeeze로 날리면 값을 얻어올 수 있다
dim값은 내가 없앨 축이라고 생각하면 이해가 쉽다
"""
tensor = torch.Tensor([[[1, 2, 3],
                        [4, 5, 6]]])
C, H, W = tensor.shape

dim1 = tensor.gather(1, torch.tensor([1, 0, 1]).view(C, -1, W)).squeeze(1)
print(f"dim1: {dim1}")
dim2 = tensor.gather(2, torch.tensor([2, 1]).view(C, H, -1)).squeeze(2)
print(f"dim2: {dim2}")

dim1: tensor([[4., 2., 6.]])
dim2: tensor([[3., 5.]])


In [3]:
"""
scatter
gather과 비슷하게 동작하지만 값을 가져오는게 아니라 target에 할당한다
"""
tensor = torch.Tensor([[[1, 2, 3],
                        [4, 5, 6]]])
C, H, W = tensor.shape

target = torch.zeros((C, H, W))
index = torch.tensor([1, 0, 1, 0, 1, 0]).view(C, -1, W)

print(f"target\n{target}")
print(f"index\n{index}")
print(f"dim1\n{target.scatter(1, index, tensor)}")

target
tensor([[[0., 0., 0.],
         [0., 0., 0.]]])
index
tensor([[[1, 0, 1],
         [0, 1, 0]]])
dim1
tensor([[[4., 2., 6.],
         [1., 5., 3.]]])


In [4]:
"""
chunk
데이터를 n등분한다
"""
tensor = torch.arange(10).view(5, -1)
print(f"원본:\n{tensor}")
print(f"5등분\n{tensor.chunk(5)}")
print(f"세로로 2등분\n{tensor.chunk(2, 1)}")

원본:
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
5등분
(tensor([[0, 1]]), tensor([[2, 3]]), tensor([[4, 5]]), tensor([[6, 7]]), tensor([[8, 9]]))
세로로 2등분
(tensor([[0],
        [2],
        [4],
        [6],
        [8]]), tensor([[1],
        [3],
        [5],
        [7],
        [9]]))


In [5]:
"""
clamp
tensor의 min과 max를 제한한다(비슷한 함수 많음)
"""
tensor = torch.randn(5)
print(f"원본\n{tensor}")
print(f"clamp\n{tensor.clamp(min=-0.3, max=0.3)}")

원본
tensor([ 1.4982, -0.5735, -0.8640, -0.2532,  0.9750])
clamp
tensor([ 0.3000, -0.3000, -0.3000, -0.2532,  0.3000])


In [6]:
"""
argmax
제일 큰 값의 index를 반환
dim 값은 없어질 축이라고 생각하면 됨(0이면 행이 다 합쳐지면서 최대 index 찾는 식)
"""
tensor = torch.randperm(10).view(2, -1) # 10보다 작은 정수 순열
print(f"텐서\n{tensor}")
print(f"argmax: {tensor.argmax(0)}")
H, W = tensor.shape
print(f"argmax 텐서\n{tensor.gather(0, tensor.argmax(0).view(-1, W)).squeeze(0)}")

텐서
tensor([[8, 2, 9, 0, 6],
        [4, 3, 7, 1, 5]])
argmax: tensor([0, 1, 0, 1, 0])
argmax 텐서
tensor([8, 3, 9, 1, 6])


In [8]:
"""
einsum
사용법을 좀 더 공부해보자
"""
tensor = torch.tensor([[1,2,3], 
                       [4,5,6]])
print(torch.einsum("ij->ji", tensor))

tensor([[1, 4],
        [2, 5],
        [3, 6]])
